// src/components/analysis/scoutingreport.jsx
// THE SCOUTING REPORT — the sell-layer OPPORTUNITY surface (native, not a Flourish embed).
// Spec: specs/sell-layer-opportunity-architecture.md §6a (FORM) + §6b (rollup) · specs/lens-contract.md
//
// This is the STOREFRONT: forward-leaning, singular, persuasive on top — with the proof door
// (drill-down to the source lens) one click beneath every claim. It renders a report built by
// src/engine/scoutingreport.js; it NEVER computes a metric or a takeaway itself (render-only sink).
//
// STYLE: conforms to specs/lens-style-standard.md — #000 bg, IBM Plex Mono, #FFF text, lime marks
// the live edge only, 0-decimal numbers. No new design decisions (§15) — Founder owns type/motion/
// color refinement; this lays out the locked tokens into the spec's seven parts.
//
// THE SEVEN PARTS (spec §6a):
//   1. Header — "Scouting Report" + Export / Copy link
//   2. Provenance — generated-by + timestamp (Observation Law)
//   3. Vitals — the domain's macro key-values
//   4. Score row — composite leverage (multiplicative, §18) with coverage
//   5. Prose summary — the macro read
//   6. Key Takeaways — each cited to a source lens (the sell-to-proof hinge)
//   7. Expandable detail rows — the drilled receipts behind the summary
import React, { useState } from 'react';

const MONO = "'IBM Plex Mono', monospace";
const LIME = '#66FF00';
const WHITE = '#FFFFFF';
const DIM = 'rgba(255,255,255,0.45)';
const FAINT = 'rgba(255,255,255,0.22)';
const HAIR = 'rgba(255,255,255,0.12)'; // hairline dividers on black (no-fill card pattern)

const pct = n => (Number.isFinite(n) ? `${Math.round(n * 100)}` : '—'); // 0 decimals (§ style)
const ts = ms => (Number.isFinite(ms) ? new Date(ms).toISOString().replace('T', ' ').slice(0, 19) + ' UTC' : '—');

// Lime marks the live edge ONLY (§6 color law). A leverage read is "live" in its top band.
const leverageIsLive = lev => lev?.state === 'GROUNDED' && Number.isFinite(lev.value) && lev.value >= 0.60;

function Header({ report, onExport, onCopyLink }) {
  return (
    <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 16 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}>
        <span style={{ fontFamily: MONO, fontSize: 18, letterSpacing: '0.12em', color: WHITE }}>
          {report.title}
        </span>
        <span style={{ fontFamily: MONO, fontSize: 11, letterSpacing: '0.22em', color: LIME }}>
          {String(report.domain ?? '').toUpperCase()}
        </span>
      </div>
      <div style={{ display: 'flex', gap: 8 }}>
        <ActionButton label="EXPORT" onClick={onExport} />
        <ActionButton label="COPY LINK" onClick={onCopyLink} />
      </div>
    </div>
  );
}

function ActionButton({ label, onClick }) {
  return (
    <button onClick={onClick}
      style={{ background: 'transparent', border: `1px solid ${HAIR}`, color: DIM,
               fontFamily: MONO, fontSize: 9, letterSpacing: '0.18em', padding: '6px 10px',
               cursor: 'pointer' }}>
      {label}
    </button>
  );
}

function Provenance({ report }) {
  return (
    <div style={{ fontFamily: MONO, fontSize: 9, letterSpacing: '0.1em', color: FAINT }}>
      GENERATED BY {String(report.generatedBy ?? '').toUpperCase()} · {ts(report.generatedAt)}
    </div>
  );
}

function Vitals({ vitals }) {
  const entries = Object.entries(vitals ?? {});
  if (!entries.length) return null;
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 28px', paddingTop: 4 }}>
      {entries.map(([k, v]) => (
        <div key={k} style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.16em', color: FAINT }}>{k.toUpperCase()}</span>
          <span style={{ fontFamily: MONO, fontSize: 14, color: WHITE }}>
            {typeof v === 'number' ? (Number.isInteger(v) ? v : v.toFixed(2)) : String(v)}
          </span>
        </div>
      ))}
    </div>
  );
}

// Score row — composite leverage + its components (§18 requires components always visible).
function ScoreRow({ leverage }) {
  const live = leverageIsLive(leverage);
  const absent = leverage?.state !== 'GROUNDED';
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: 32, borderTop: `1px solid ${HAIR}`,
                  borderBottom: `1px solid ${HAIR}`, padding: '14px 0' }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.16em', color: FAINT }}>LEVERAGE</span>
        <span style={{ fontFamily: MONO, fontSize: 34, lineHeight: 1, color: live ? LIME : WHITE }}>
          {absent ? '—' : pct(leverage.value)}
        </span>
        <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.1em', color: FAINT }}>
          {absent ? 'NO GROUNDED READ' : `${leverage.groundedCount}/${leverage.lensCount} LENSES · ${pct(leverage.coverage)}% COVERAGE`}
        </span>
      </div>
      {/* components — the number is re-derivable from these (§18) */}
      <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap' }}>
        {(leverage?.components ?? []).map(c => (
          <div key={c.lens} style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.12em', color: FAINT }}>{c.lens}</span>
            <span style={{ fontFamily: MONO, fontSize: 14, color: WHITE }}>{pct(c.value)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function Prose({ text }) {
  return (
    <p style={{ fontFamily: MONO, fontSize: 13, lineHeight: 1.6, color: 'rgba(255,255,255,0.82)', margin: 0, maxWidth: 760 }}>
      {text}
    </p>
  );
}

// A single takeaway: forward-leaning line + its citation tag. Clicking expands the receipt —
// that expansion IS the sell-to-proof door: the storefront line, one click from its ledger read.
function Takeaway({ t }) {
  const [open, setOpen] = useState(false);
  const withheld = t.state === 'WITHHELD';
  return (
    <div style={{ borderTop: `1px solid ${HAIR}`, padding: '10px 0' }}>
      <button onClick={() => setOpen(o => !o)}
        style={{ display: 'flex', alignItems: 'baseline', gap: 10, width: '100%', textAlign: 'left',
                 background: 'transparent', border: 'none', cursor: 'pointer', padding: 0 }}>
        <span style={{ fontFamily: MONO, fontSize: 12, color: FAINT, width: 12, flexShrink: 0 }}>{open ? '–' : '+'}</span>
        <span style={{ fontFamily: MONO, fontSize: 12.5, lineHeight: 1.55,
                       color: withheld ? DIM : 'rgba(255,255,255,0.86)', flex: 1 }}>
          {t.text}
        </span>
        <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.14em',
                       color: withheld ? FAINT : LIME, flexShrink: 0,
                       border: `1px solid ${withheld ? HAIR : 'rgba(102,255,0,0.35)'}`, padding: '2px 6px' }}>
          [{t.citation}]
        </span>
      </button>
      {open && (
        <div style={{ marginLeft: 22, marginTop: 8, paddingLeft: 12, borderLeft: `1px solid ${HAIR}` }}>
          <div style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.14em', color: FAINT, marginBottom: 6 }}>
            {withheld ? `WITHHELD · ${t.absence ?? ''} ABSENCE` : 'RECEIPT'} — DRILLS TO {t.citation} LENS
          </div>
          <Receipt receipt={t.drill} />
        </div>
      )}
    </div>
  );
}

// The raw grounded read the citation resolves to — the proof, printed as key/values.
function Receipt({ receipt }) {
  const entries = Object.entries(receipt ?? {}).filter(([, v]) => v != null && v !== '');
  if (!entries.length) return <span style={{ fontFamily: MONO, fontSize: 10, color: FAINT }}>no receipt</span>;
  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '3px 14px' }}>
      {entries.map(([k, v]) => (
        <React.Fragment key={k}>
          <span style={{ fontFamily: MONO, fontSize: 9, letterSpacing: '0.08em', color: FAINT }}>{k}</span>
          <span style={{ fontFamily: MONO, fontSize: 10, color: 'rgba(255,255,255,0.75)' }}>{String(v)}</span>
        </React.Fragment>
      ))}
    </div>
  );
}

function EmptyState({ report }) {
  return (
    <div style={{ fontFamily: MONO, fontSize: 11, letterSpacing: '0.08em', color: DIM, lineHeight: 1.6 }}>
      No grounded lens read on {String(report.domain ?? '').toUpperCase()} yet.
      <div style={{ fontSize: 9, color: FAINT, marginTop: 6 }}>
        {report.unsupplied?.length ? `AWAITING: ${report.unsupplied.join(' · ')}` : ''}
      </div>
    </div>
  );
}

/**
 * ScoutingReport — render one report object from src/engine/scoutingreport.js.
 * @param {{report: object, onExport?:Function, onCopyLink?:Function}} props
 */
export default function ScoutingReport({ report, onExport, onCopyLink }) {
  if (!report) return null;
  const noGrounded = !report.takeaways?.some(t => t.state === 'GROUNDED');

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14, width: '100%', height: '100%',
                  overflowY: 'auto', padding: '4px 2px', boxSizing: 'border-box' }}>
      <Header report={report} onExport={onExport} onCopyLink={onCopyLink} />
      <Provenance report={report} />
      <Vitals vitals={report.vitals} />
      <ScoreRow leverage={report.leverage} />
      <Prose text={report.summary} />
      <div>
        <div style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.2em', color: FAINT, marginBottom: 2 }}>
          KEY TAKEAWAYS
        </div>
        {noGrounded && !report.takeaways?.length
          ? <EmptyState report={report} />
          : report.takeaways.map((t, i) => <Takeaway key={`${t.lens}-${i}`} t={t} />)}
      </div>
    </div>
  );
}
