// src/components/analysis/scoutingreport.jsx
// KRYLO DOMAIN INTELLIGENCE SURFACE (DIS) — the sell-layer OPPORTUNITY surface.
// Spec: "KRYLO Domain Intelligence Surface v1.0" (Founder, 2026-07-24) · lens-contract.md
//
// Renders a Domain Intelligence Brief (src/engine/domainbrief.js). Render-only sink: it NEVER
// computes a value or a state — the engine decides, React draws.
//
// INFORMATION ARCHITECTURE (CB Insights model — borrowed for structure, not look):
//   Insight → State → Forces → Patterns → Relationships → Contradictions → Unknowns → Watch → Evidence.
//   Conclusion first, evidence last, progressive disclosure (each section drills to its receipt).
//
// STYLE: lens-style-standard.md (LOCKED) — #000 ground, IBM Plex Mono, #FFF text, #66FF00 lime marks
// the LIVE structural state only, 0-decimal numbers. No new design decisions (§15).
//
// ALL LIVE DATA: a WITHHELD section renders as classified absence — never a fabricated value.
import React, { useState } from 'react';

const MONO  = "'IBM Plex Mono', monospace";
const LIME  = '#66FF00';
const WHITE = '#FFFFFF';
const DIM   = 'rgba(255,255,255,0.55)';
const FAINT = 'rgba(255,255,255,0.28)';
const GHOST = 'rgba(255,255,255,0.14)';
const HAIR  = 'rgba(255,255,255,0.12)';

const pct = n => (Number.isFinite(n) ? `${Math.round(n * 100)}` : '—');
const tstamp = ms => (Number.isFinite(ms) ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' UTC' : '—');
// lime = live structural state ONLY (§6). Anything not live/measured stays neutral.
const liveHue = live => (live ? LIME : DIM);

// ── header: the conclusion, first (CB Insights: intelligence-first) ─────────────────────────────
function Header({ brief }) {
  const h = brief.header;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, paddingBottom: 14, borderBottom: `1px solid ${HAIR}` }}>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 16 }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          <span style={{ fontFamily: MONO, fontSize: 9, letterSpacing: '0.28em', color: FAINT }}>
            DOMAIN INTELLIGENCE BRIEF
          </span>
          <span style={{ fontFamily: MONO, fontSize: 26, letterSpacing: '0.02em', color: WHITE, lineHeight: 1 }}>
            {brief.domain}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Btn label="EXPORT" /><Btn label="COPY LINK" />
        </div>
      </div>

      {/* state · confidence · momentum · coverage — grounded readouts, lime only when live */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px 34px', alignItems: 'flex-end' }}>
        <Stat label="STRUCTURAL STATE" value={h.state} hue={liveHue(brief.live)} big />
        <Stat label="CONFIDENCE" value={h.confidence == null ? '—' : `${pct(h.confidence)}%`} />
        <Stat label="FIELD-RELATIVE" value={h.momentum ? h.momentum.value : '—'}
              sub={h.momentum ? 'CROSS-SECTIONAL' : ''} />
        <Stat label="EVIDENCE" value={`${h.coverage.signalCount} SIGNAL${h.coverage.signalCount === 1 ? '' : 'S'}`}
              sub={`${h.coverage.activeDomains}/6 DOMAINS ACTIVE`} />
      </div>
      <div style={{ fontFamily: MONO, fontSize: 8.5, letterSpacing: '0.12em', color: FAINT }}>
        GENERATED BY {String(brief.generatedBy).toUpperCase()} · {tstamp(brief.generatedAt)} · {brief.coverage.grounded}/{brief.coverage.total} SECTIONS GROUNDED
      </div>
    </div>
  );
}

function Stat({ label, value, sub, hue = WHITE, big }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.16em', color: FAINT }}>{label}</span>
      <span style={{ fontFamily: MONO, fontSize: big ? 16 : 14, color: hue, letterSpacing: '0.02em' }}>{value}</span>
      {sub ? <span style={{ fontFamily: MONO, fontSize: 7.5, letterSpacing: '0.12em', color: FAINT }}>{sub}</span> : null}
    </div>
  );
}
function Btn({ label }) {
  return (
    <button style={{ background: 'transparent', border: `1px solid ${GHOST}`, color: DIM,
                     fontFamily: MONO, fontSize: 8.5, letterSpacing: '0.18em', padding: '6px 10px', cursor: 'pointer' }}>
      {label}
    </button>
  );
}

// ── a section card — one question, answered or explicitly withheld, drills to its receipt ───────
function Section({ s, index }) {
  const [open, setOpen] = useState(false);
  const isWithheld = s.state === 'WITHHELD';
  return (
    <div style={{ borderBottom: `1px solid ${HAIR}`, padding: '13px 0' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}>
        <span style={{ fontFamily: MONO, fontSize: 9, color: FAINT, width: 20, flexShrink: 0 }}>
          {String(index + 1).padStart(2, '0')}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 10 }}>
            <span style={{ fontFamily: MONO, fontSize: 10, letterSpacing: '0.14em', color: DIM }}>
              {s.title.toUpperCase()}
            </span>
            <button onClick={() => setOpen(o => !o)}
              style={{ background: 'transparent', border: 'none', cursor: 'pointer', padding: 0,
                       fontFamily: MONO, fontSize: 8, letterSpacing: '0.14em',
                       color: isWithheld ? FAINT : LIME,
                       borderBottom: `1px solid ${isWithheld ? HAIR : 'rgba(102,255,0,0.35)'}` }}>
              [{s.citation ?? s.absence}] {open ? '−' : '+'}
            </button>
          </div>
          <div style={{ marginTop: 6 }}>
            {isWithheld ? <Withheld s={s} /> : <Grounded s={s} />}
          </div>
          {open && (
            <div style={{ marginTop: 10, paddingLeft: 12, borderLeft: `1px solid ${HAIR}` }}>
              <div style={{ fontFamily: MONO, fontSize: 7.5, letterSpacing: '0.16em', color: FAINT, marginBottom: 6 }}>
                {isWithheld ? `WITHHELD · ${s.absence} ABSENCE` : `RECEIPT · DRILLS TO ${s.citation} LENS`}
              </div>
              <Receipt receipt={s.drill} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// grounded body — renders whichever grounded shape the section carries
function Grounded({ s }) {
  const T = { fontFamily: MONO, fontSize: 12.5, lineHeight: 1.55, color: 'rgba(255,255,255,0.85)' };
  if (s.text) return <p style={{ ...T, margin: 0 }}>{s.text}</p>;

  if (s.id === 'STRUCTURAL_STATE') {
    return (
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 24px' }}>
        <Mini label="STATE" value={s.value} hue={LIME} />
        <Mini label="DIRECTION" value={s.direction ?? '—'} />
        <Mini label="CONFIDENCE" value={`${pct(s.confidence)}%`} />
        <Mini label="TRAJECTORY" value="WITHHELD" hue={FAINT} sub="temporal" />
      </div>
    );
  }
  if (s.id === 'CROSS_DOMAIN_INFLUENCE') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
        {s.standings.map(o => (
          <div key={o.domain} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontFamily: MONO, fontSize: 11, color: WHITE, width: 96 }}>{o.domain}</span>
            <Bar value={o.magnitude} polarity={o.polarity} />
            <span style={{ fontFamily: MONO, fontSize: 10, color: DIM, width: 30, textAlign: 'right' }}>{Math.round(o.magnitude)}</span>
          </div>
        ))}
        <span style={{ fontFamily: MONO, fontSize: 8, letterSpacing: '0.1em', color: FAINT, marginTop: 2 }}>
          AMPLIFY/SUPPRESS DIRECTION WITHHELD — NO DIRECTED FLOW
        </span>
      </div>
    );
  }
  if (s.id === 'UNKNOWNS') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {s.items.length === 0
          ? <span style={{ ...T }}>Every section grounded — nothing withheld.</span>
          : s.items.map((it, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, fontFamily: MONO, fontSize: 11, color: DIM }}>
                <span style={{ color: FAINT, width: 150 }}>{it.section}</span>
                <span style={{ color: FAINT }}>{it.absence}</span>
                <span>{it.reason}</span>
              </div>
            ))}
      </div>
    );
  }
  return <p style={{ ...T, margin: 0 }}>{JSON.stringify(s.value ?? s)}</p>;
}

function Withheld({ s }) {
  return (
    <p style={{ fontFamily: MONO, fontSize: 12, lineHeight: 1.5, color: DIM, margin: 0 }}>
      {s.question} — <span style={{ color: FAINT }}>withheld.</span> {s.reason.replace(/_/g, ' ').toLowerCase()}.
    </p>
  );
}

function Mini({ label, value, hue = WHITE, sub }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      <span style={{ fontFamily: MONO, fontSize: 7.5, letterSpacing: '0.14em', color: FAINT }}>{label}</span>
      <span style={{ fontFamily: MONO, fontSize: 12, color: hue }}>{value}</span>
      {sub ? <span style={{ fontFamily: MONO, fontSize: 7, color: FAINT }}>{sub}</span> : null}
    </div>
  );
}
function Bar({ value, polarity }) {
  const w = Math.max(2, Math.min(100, value));
  const hue = polarity === 'fracture' ? 'rgba(255,255,255,0.4)' : LIME;
  return (
    <div style={{ flex: 1, height: 4, background: 'rgba(255,255,255,0.08)', position: 'relative', maxWidth: 220 }}>
      <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: `${w}%`, background: hue, opacity: 0.75 }} />
    </div>
  );
}
function Receipt({ receipt }) {
  const entries = Object.entries(receipt ?? {}).filter(([, v]) => v != null && v !== '' && typeof v !== 'object');
  if (!entries.length) return <span style={{ fontFamily: MONO, fontSize: 10, color: FAINT }}>no receipt</span>;
  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '3px 16px' }}>
      {entries.map(([k, v]) => (
        <React.Fragment key={k}>
          <span style={{ fontFamily: MONO, fontSize: 9, letterSpacing: '0.06em', color: FAINT }}>{k}</span>
          <span style={{ fontFamily: MONO, fontSize: 10, color: 'rgba(255,255,255,0.78)' }}>{String(v)}</span>
        </React.Fragment>
      ))}
    </div>
  );
}

/**
 * ScoutingReport — renders a Domain Intelligence Brief (src/engine/domainbrief.js).
 * (Filename retained for the OPPORTUNITY-lens mount; the surface is the Domain Intelligence Brief.)
 */
export default function ScoutingReport({ report }) {
  if (!report) return null;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 4, width: '100%', height: '100%',
                  overflowY: 'auto', padding: '6px 4px', boxSizing: 'border-box' }}>
      <Header brief={report} />
      {report.sections.map((s, i) => <Section key={s.id} s={s} index={i} />)}
    </div>
  );
}
